// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXsQk4no7fFlUPtKtIAbLQjD1tkeNif4Q',
    appId: '1:745683826599:web:7ce6e37c2b547453e32882',
    messagingSenderId: '745683826599',
    projectId: 'todo-list-app-a3be9',
    authDomain: 'todo-list-app-a3be9.firebaseapp.com',
    storageBucket: 'todo-list-app-a3be9.appspot.com',
    measurementId: 'G-1MGQ6XF8CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByAo9YWjj_ZMUwDT_RUD8tvIlrTatwDKk',
    appId: '1:745683826599:android:08f0416047998aa8e32882',
    messagingSenderId: '745683826599',
    projectId: 'todo-list-app-a3be9',
    storageBucket: 'todo-list-app-a3be9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCStm5Iavf82iRKjA5JYd9vv-gNQ4mPudA',
    appId: '1:745683826599:ios:8f2f717bc61f8019e32882',
    messagingSenderId: '745683826599',
    projectId: 'todo-list-app-a3be9',
    storageBucket: 'todo-list-app-a3be9.appspot.com',
    iosClientId: '745683826599-9nh7rtg4ifk71di6c4u8uoe3q1rsqa5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCStm5Iavf82iRKjA5JYd9vv-gNQ4mPudA',
    appId: '1:745683826599:ios:524268d3bc564108e32882',
    messagingSenderId: '745683826599',
    projectId: 'todo-list-app-a3be9',
    storageBucket: 'todo-list-app-a3be9.appspot.com',
    iosClientId: '745683826599-vleogcr6gctodjchc362ko6sg7td03g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
